global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets: ['192.168.99.203:9090']
  - job_name: 'pipelines'
    static_configs:
    - targets: ['192.168.99.201:9100']
  - job_name: 'containers'
    static_configs:
    - targets: ['192.168.99.202:9100']
  - job_name: 'docker'
    static_configs:
    - targets: ['192.168.99.202:9323']