- name: Debian - Install Apache HTTP Server and php
  apt: 
    name: 
      - apache2
      - php
      - php-mysqlnd
    state: latest
    update_cache: true
    
- name: Debian - Start and Enable Apache HTTP Server
  service: 
    name: apache2 
    state: started 
    enabled: true

- name: Remove index.html
  file:
    path: /var/www/html/index.html
    state: absent

- name: Debian - Copy web content
  copy:
    src: /home/vagrant/2/m2hw/web/
    dest: /var/www/html/
    remote_src: no