# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    
  config.ssh.insert_key = false
  
  config.vm.define "node1" do |node3|
    node3.vm.box="shekeriev/centos-stream-9"
    node3.vm.hostname = "node1.do1.lab"
    node3.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048"]
    end
    node3.vm.network "private_network", ip: "192.168.99.101"
	node3.vm.provision "shell", path: "add_hosts.sh"
    node3.vm.provision "shell", path: "install_docker_centos.sh"
  end

end
