# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    
  config.ssh.insert_key = false

  config.vm.define "ans" do |ans|
    ans.vm.box = "shekeriev/centos-stream-9"
    ans.vm.hostname = "ans.do2.lab"
    ans.vm.network "private_network", ip: "192.168.99.99"
    ans.vm.synced_folder "vagrant/", "/vagrant"
    ans.vm.provision "shell", inline: <<EOS
dnf install -y ansible-core
ansible-galaxy collection install -p /usr/share/ansible/collections ansible.posix
ansible-galaxy collection install -p /usr/share/ansible/collections community.general
ansible-galaxy collection install -p /usr/share/ansible/collections community.docker
ansible-galaxy collection install -p /usr/share/ansible/collections community.mysql
EOS
  end

  config.vm.define "docker" do |docker|
    docker.vm.box = "shekeriev/centos-stream-9"
    docker.vm.hostname = "docker.do2.lab"
    docker.vm.network "private_network", ip: "192.168.99.100"
    docker.vm.synced_folder "vagrant/", "/vagrant"
    docker.vm.network "forwarded_port", guest: 80, host: 8080
  end

  config.vm.define "web" do |web|
    web.vm.box = "shekeriev/debian-11"
    web.vm.hostname = "web.do2.lab"
    web.vm.network "private_network", ip: "192.168.99.101"
    web.vm.synced_folder "vagrant/", "/vagrant"
    web.vm.network "forwarded_port", guest: 80, host: 8080
    web.vm.provision "shell", path: "add_hosts.sh"
  end

  config.vm.define "db" do |db|
    db.vm.box = "shekeriev/centos-stream-9"
    db.vm.hostname = "db.do2.lab"
    db.vm.network "private_network", ip: "192.168.99.102"
    db.vm.synced_folder "vagrant/", "/vagrant"
    db.vm.provision "shell", path: "add_hosts.sh"
  end
 
end
